export default [
	{
		title: 'Chamonix',
		location: 'France',
		googleMapsUrl: 'https://maps.app.goo.gl/Anv59UHtbpdd7ZFL6',
		startDate: '03 Feb, 2003',
		endDate: '10 Feb, 2003',
		description:
			'Chamonix is located in the Valley of Chamonix-Mont-Blanc, offering amazing skiing. The photo shows The Aiguille du Midi, "Needle at midday". It is a popular tourist destination and can be directly accessed by cable car from Chamonix.',
		image: '03-chamonix.png',
	},
	{
		title: 'Dorset',
		location: 'England',
		googleMapsUrl: 'https://maps.app.goo.gl/WKwrxRGPGBXthg9b8',
		startDate: '16 Jul, 2005',
		endDate: '21 Jul, 2005',
		description:
			'Dorset is a county in South West England, with largest town Dorchester. Corfe Castle One of Britains most iconic and evocative survivors of the English Civil War, partially demolished in 1646 by the Parliamentarians.',
		image: '05-swanage.png',
	},
	{
		title: 'Alpes-Maritimes',
		location: 'France',
		googleMapsUrl: '',
		startDate: '1 Jul, 20',
		endDate: '2 Jul, 20',
		description: '.',
		image: '06-alpes-maritime.png',
	},
	{
		title: '',
		location: '',
		googleMapsUrl: '',
		startDate: '1 Jul, 20',
		endDate: '2 Jul, 20',
		description: '.',
		image: '08-gotland.png',
	},
	{
		title: '',
		location: 'France',
		googleMapsUrl: '',
		startDate: '1 Jul, 20',
		endDate: '2 Jul, 20',
		description: '.',
		image: '09-provence.png',
	},
	{
		title: 'Stonehenge',
		location: 'England',
		googleMapsUrl: '',
		startDate: '1 Jul, 20',
		endDate: '2 Jul, 20',
		description: '.',
		image: '11-stonehenge.png',
	},
	{
		title: 'Parga',
		location: 'Greece',
		googleMapsUrl: '',
		startDate: '1 Jul, 20',
		endDate: '2 Jul, 20',
		description: '.',
		image: '13-greece.png',
	},
]
